// Preset catalog for the UI. Data file generated by scripts/extract-cc-switch-presets.mjs.
// Featured list: hand-picked well-known providers, shown first in the preset picker.

import {
  PRESET_META,
  ANTHROPIC_PRESETS,
  OPENAI_PRESETS,
  UA_PRESETS,
  UNSUPPORTED_PRESETS,
} from './presets-data.mjs';

// Featured entries are matched by name against both catalogs.
const FEATURED_NAMES = [
  'Kimi',
  'Kimi For Coding',
  'DeepSeek',
  'Zhipu GLM',
  'Baidu Qianfan Coding Plan',
  'Baidu Qianfan Token Plan',
  'SiliconFlow',
  'SiliconFlow en',
  'MiniMax',
  'StepFun',
  'Longcat',
  'ModelScope',
  ' Agent Plan',
  ' Coding Plan',
  'DouBaoSeed',
  'OpenRouter',
  'Moonshot Kimi',
  'Zhipu GLM en',
];

export function listPresets() {
  const anthropic = ANTHROPIC_PRESETS.map((p) => ({ ...p }));
  const openai = OPENAI_PRESETS.map((p) => ({ ...p }));
 const featuredNames = new Set(FEATURED_NAMES);
 const featured = [];
 for (const name of FEATURED_NAMES) {
    const a = anthropic.find((p) => p.name === name);
    const o = openai.find((p) => p.name === name);
    const hit = a ?? o;
    if (hit) featured.push({ ...hit, featured: true });
  }
  return {
    meta: PRESET_META,
    anthropic,
    openai,
    featured,
    uaPresets: UA_PRESETS,
    unsupported: UNSUPPORTED_PRESETS,
  };
}

// Build a channel draft from a preset (name match across catalogs).
export function presetToChannel(presetName) {
  const p =
    ANTHROPIC_PRESETS.find((x) => x.name === presetName) ??
    OPENAI_PRESETS.find((x) => x.name === presetName);
  if (!p) return null;
  return {
    name: p.name,
    protocol: p.protocol ?? 'anthropic',
    base_url: p.baseUrl ?? '',
    auth_mode: p.authMode ?? 'bearer',
    models: (p.defaultModels ?? []).join(','),
    notes: '' + (p.verified ? '' : ''),
  };
}